apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: paysentinel
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/paysentinel*.log
        Parser            docker
        Tag               paysentinel.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB

    [FILTER]
        Name   record_modifier
        Match  paysentinel.*
        Record cluster paysentinel-eks
        Record environment production

    [OUTPUT]
        Name        splunk
        Match       paysentinel.*
        Host        SPLUNK_HEC_HOST
        Port        8088
        Splunk_Token SPLUNK_HEC_TOKEN
        TLS         On
        TLS.Verify  Off

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
