apiVersion: v1
kind: Service
metadata:
  name: paysentinel
  namespace: paysentinel
  labels:
    app: paysentinel
spec:
  type: LoadBalancer
  selector:
    app: paysentinel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
